[package]
name = "oasis-platform"
description = "Platform service abstractions for OASIS_OS"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
oasis-types = { workspace = true }

[lints]
workspace = true
