background = "#003399"
primary = "#003399"
secondary = "#1F3E7B"
text = "#FFFFFF"
dim_text = "#8899BB"
status_bar = "#1F3E7B"
prompt = "#FFFFFF"
output = "#FFFFFF"
error = "#FF0000"
border_radius = 3
shadow_intensity = 1
gradient_enabled = true

[wm_theme]
titlebar_height = 24
border_width = 1
titlebar_active = "#0054E3"
titlebar_inactive = "#7B7B7B"
titlebar_text = "#FFFFFF"
frame_color = "#0054E3"
content_bg = "#ECE9D8"
btn_close = "#C75050"
btn_minimize = "#406BBD"
btn_maximize = "#406BBD"
button_size = 16
titlebar_font_size = 12
titlebar_radius = 4
titlebar_gradient = true
titlebar_gradient_top = "#3A6EA5"
titlebar_gradient_bottom = "#0A246A"
titlebar_inactive_gradient_top = "#B4B4B4"
titlebar_inactive_gradient_bottom = "#7B7B7B"
frame_shadow_level = 1
frame_border_radius = 3
button_radius = 2
button_side = "right"
glyph_close = "x"
glyph_minimize = "_"
glyph_maximize = "o"
title_align = "left"
separator_enabled = true
separator_color = "#0054E340"
glyph_close_color = "#FFFFFF"
glyph_minimize_color = "#FFFFFF"
glyph_maximize_color = "#FFFFFF"
btn_close_hover = "#E66060"
btn_minimize_hover = "#5080D0"
btn_maximize_hover = "#5080D0"
title_text_shadow = true
title_text_shadow_color = "#00000060"
content_stroke_width = 1
content_stroke_color = "#0054E320"
maximize_top_inset = 44
maximize_bottom_inset = 30

[bar_overrides]
statusbar_bg = "#1F3E7B"
statusbar_gradient_top = "#3169C6"
statusbar_gradient_bottom = "#1F3E7B"
bar_bg = "#1F3E7B"
bar_gradient_top = "#3169C6"
bar_gradient_bottom = "#1F3E7B"
battery_color = "#FFFFFF"
version_color = "#FFFFFF"
clock_color = "#FFFFFF"
separator_color = "#4080D0"

[wallpaper]
style = "gradient"
color_stops = ["#003399", "#1F5FC2", "#3A8AE0", "#5BB5FF"]
wave_enabled = false
angle = 90

[geometry]
statusbar_height = 26
bottombar_height = 30
icon_width = 24
icon_height = 28

[icon_overrides]
body_color = "#ECE9D8"
fold_color = "#C8C2AD"
outline_color = "#0054E380"
label_color = "#000000E6"
cursor_color = "#003399C0"
icon_border_radius = 3
cursor_border_radius = 4
icon_style = "card"
cursor_style = "fill"

[start_menu_overrides]
panel_bg = "#1F3E7B"
panel_gradient_top = "#3169C6"
panel_gradient_bottom = "#0A246A"
panel_border = "#4080D0"
item_text = "#FFFFFF"
item_text_active = "#FFFFFF"
highlight_color = "#3A6EA580"
button_bg = "#309E30"
button_text = "#FFFFFF"
panel_border_radius = 4
panel_shadow_level = 1
button_label = "start"
button_width = 54
button_height = 22
button_shape = "rect"
button_gradient = true
button_gradient_top = "#4DA54D"
button_gradient_bottom = "#2D852D"
panel_width = 240
columns = 2
header_text = "User"
header_bg = "#003399"
header_text_color = "#FFFFFF"
header_height = 28
footer_enabled = true
footer_bg = "#1F3E7B"
footer_text_color = "#FFFFFF"
footer_height = 24
item_icon_size = 16
item_row_height = 24

[browser_overrides]
chrome_bg = "#D6D2C2"
chrome_text = "#000000"
chrome_button_bg = "#ECE9D8"
url_bar_bg = "#FFFFFF"
url_bar_text = "#000000"
link_color = "#0066CC"
